#!/usr/bin/env python3
# inkflow · scripts/extract_font.py
#
# Render a subset of CJK characters from a TTF/TTC into 4bpp packed
# bitmaps and emit a Rust source file with `static GLYPHS`.
#
# Usage:  python3 extract_font.py /path/to/NotoSansCJK-Regular.ttc
#
# Hard-coded subset is the union of POOLS in main.rs (静 / 动 / 冷 / 暖)
# plus ASCII printable + space + a few atmospheric extras. Bumping
# the subset increases binary size roughly linearly — keep it tight.

import sys
from PIL import Image, ImageFont

# Glyph source size — the rendered cell after font extraction. Larger = nicer
# glyphs but more bytes per glyph in the binary.
GLYPH_W = 48
GLYPH_H = 48

# ----- subset -----
# Built from the POOLS in main.rs + the visible ASCII range + a handful of
# poetic extras. Every char here costs ~1.2 KB in the binary (48*48/2 bytes).
SUBSET = (
    # quiet pool (静)
    "雾月夜潮呼吸微光深处沉睡鲸落尘埃影钟摆雨前纸页苔林木叶泉"
    "雪落远钟云根幽径落花鸿影薄暮清露听蝉听雪"
    # moving pool (动)
    "风焰河奔裂帛星陨心跳浪尖闪电迁徙鼓惊鸟火渡口弦雷潮涌雷鸣"
    "烟火龙吟震颤飞溅雪崩迸裂翻涌流火疾行"
    # cold pool (冷)
    "雪蓝冰星霜铁墨深空孤井石英冬海沟玻璃月背银寒朔风凝霜寒潭"
    "远岭苍凛薄冰星河落雪静海"
    # warm pool (暖)
    "灯橘麦陶体温琥珀黄昏花信茧炊烟蜜绒烛岸掌心茶暖炉火夕照"
    "茶烟旧书木质余温棉晨曦晚风"
    # poetic extras
    "诗无云川焦"
)
SUBSET = "".join(dict.fromkeys(SUBSET))  # dedupe, preserve order

# ASCII printable (no DEL) + space.
ASCII = "".join(chr(c) for c in range(32, 127))


def render_glyph(font, ch):
    """Render one char into a GLYPH_W × GLYPH_H grayscale image, return a list of
    4bpp values (0..15) packed two per byte."""
    img = Image.new("L", (GLYPH_W, GLYPH_H), 0)
    drw = ImageDraw = None
    from PIL import ImageDraw as _ID
    drw = _ID.Draw(img)
    # Anchor the glyph at the visual baseline of the cell. Pillow's default
    # bitmap font drawing places text with its top-left at (0, 0), so we
    # pre-rasterise onto a wider canvas and crop the cell so glyphs sit
    # centred without clipping.
    canvas = Image.new("L", (GLYPH_W * 2, GLYPH_H * 2), 0)
    _cd = _ID.Draw(canvas)
    _cd.text((2, 2), ch, fill=255, font=font)
    # find the inked bbox, then paste it back into img
    bbox = canvas.getbbox()
    if not bbox:
        return [0] * (GLYPH_W * GLYPH_H)
    cropped = canvas.crop(bbox)
    # scale cropped to fit inside GLYPH_W × GLYPH_H while preserving aspect
    cw, ch_h = cropped.size
    if cw == 0 or ch_h == 0:
        return [0] * (GLYPH_W * GLYPH_H)
    scale = min(GLYPH_W / cw, GLYPH_H / ch_h)
    nw, nh = max(1, int(round(cw * scale))), max(1, int(round(ch_h * scale)))
    resized = cropped.resize((nw, nh), Image.LANCZOS)
    # paste centred into img
    px = (GLYPH_W - nw) // 2
    py = (GLYPH_H - nh) // 2
    img.paste(resized, (px, py))
    px_arr = list(img.getdata())
    # quantise to 4 bits
    return [min(15, v >> 4) for v in px_arr]


def pack4(quads):
    out = bytearray()
    for i in range(0, len(quads), 2):
        hi = quads[i] & 0xF
        lo = (quads[i + 1] if i + 1 < len(quads) else 0) & 0xF
        out.append((hi << 4) | lo)
    return bytes(out)


def rust_str_lit(s):
    """Render a Python string as a Rust &str literal."""
    out = []
    for c in s:
        cp = ord(c)
        if c == '"':
            out.append('\\"')
        elif c == '\\':
            out.append('\\\\')
        elif c == '\n':
            out.append('\\n')
        elif c == '\r':
            out.append('\\r')
        elif c == '\t':
            out.append('\\t')
        elif cp < 0x20 or cp == 0x7f:
            out.append(f"\\u{{{cp:04x}}}")
        else:
            out.append(c)
    return "".join(out)


def main():
    if len(sys.argv) < 2:
        print("usage: extract_font.py FONT_PATH", file=sys.stderr)
        sys.exit(2)
    font_path = sys.argv[1]

    # Font size chosen so most CJK glyphs fill the cell without clipping.
    # 56 px over 48 twice: LANCZOS down to 48 gives anti-aliased 8-bit gray
    # which we then quantise to 4 bits per pixel.
    font = ImageFont.truetype(font_path, 56)

    lines = []
    lines.append("// inkflow · fontdata.rs")
    lines.append("//")
    lines.append("// Auto-generated by scripts/extract-font.sh from Noto Sans CJK.")
    lines.append("// DO NOT EDIT BY HAND — re-run the script after changing the subset.")
    lines.append("")
    lines.append("#![allow(dead_code, non_snake_case)]")
    lines.append("")
    lines.append(f"pub const GLYPH_W: u32 = {GLYPH_W};")
    lines.append(f"pub const GLYPH_H: u32 = {GLYPH_H};")
    lines.append("")
    lines.append("/// (char → packed 4bpp bitmap, GLYPH_W * GLYPH_H / 2 bytes long).")
    lines.append("pub static GLYPHS: &[(&str, &[u8])] = &[")
    total = 0
    for ch in SUBSET + ASCII:
        quads = render_glyph(font, ch)
        packed = pack4(quads)
        total += len(packed)
        # Escape the char literal properly — Rust uses \u{XXXX}, not \uXXXX
        esc = rust_str_lit(ch)
        lines.append(f"    (\"{esc}\", &[" + ", ".join(str(b) for b in packed) + f"]),")
    lines.append("];")
    lines.append("")
    out = "\n".join(lines) + "\n"
    sys.stdout.write(out)
    sys.stderr.write(f"generated {len(SUBSET) + len(ASCII)} glyphs, {total} bytes\n")


if __name__ == "__main__":
    main()