//! Embedded coverage glyph renderer.
//!
//! A single pre-rendered bucket (128 px em, generated by `build_font.py` from
//! Noto Sans CJK) is area-sampled down to every target size, so edges stay
//! smooth from the hero line to the faintest supporting stroke.

use crate::color;

pub use crate::glyph_table::Glyph;

pub const HERO_EM_PX: u16 = crate::glyph_table::HERO_EM_PX;

pub use crate::glyph_table::{FONT_INDEX, GLYPH_COUNT, HERO_DATA, HERO_NOTDEF, HERO_TABLE};

/// Pen/baseline position in pixels.
pub struct Point {
    pub x: i32,
    pub y: i32,
}
impl Point {
    pub const fn new(x: i32, y: i32) -> Self {
        Self { x, y }
    }
}

/// Binary-search codepoint → glyph slot; 0 (notdef) when unmapped.
pub fn index_for(cp: u32) -> u8 {
    let mut lo = 0usize;
    let mut hi = FONT_INDEX.len();
    while lo < hi {
        let mid = (lo + hi) >> 1;
        let e = &FONT_INDEX[mid];
        if e.cp < cp {
            lo = mid + 1;
        } else if e.cp > cp {
            hi = mid;
        } else {
            return e.slot as u8;
        }
    }
    0
}

/// Render one glyph.
///
/// `fx`/`fy` are Q8 fixed-point pen position and baseline; `scale_q8` is the
/// Q8 scale relative to the bucket's native em (256 = native). Coverage is
/// area-sampled when shrinking.
#[allow(clippy::too_many_arguments)]
pub fn draw_glyph(
    fb: &mut [u32],
    w: usize,
    h: usize,
    glyph_idx: u8,
    color: u32,
    _glow: u32,
    fx: i32,
    fy: i32,
    scale_q8: u32,
    alpha: f32,
) {
    if alpha <= 0.0 {
        return;
    }
    let g = if glyph_idx == 0 {
        &HERO_NOTDEF
    } else {
        &HERO_TABLE[glyph_idx as usize]
    };
    composite_glyph(fb, w, h, g, &HERO_DATA, color, fx, fy, scale_q8, alpha);
}

#[allow(clippy::too_many_arguments)]
fn composite_glyph(
    fb: &mut [u32],
    w: usize,
    h: usize,
    g: &'static Glyph,
    data: &'static [u8],
    color: u32,
    fx: i32,
    fy: i32,
    scale_q8: u32,
    alpha: f32,
) {
    let mul = scale_q8 as i32;
    let bbox_x_q8 = fx + g.bearing_x as i32 * mul;
    let bbox_y_q8 = fy - g.bearing_y as i32 * mul;
    let bbox_w_q8 = g.w as i32 * mul;
    let bbox_h_q8 = g.h as i32 * mul;
    if bbox_w_q8 <= 0 || bbox_h_q8 <= 0 {
        return;
    }

    let x0 = (bbox_x_q8 >> 8).max(0) as usize;
    let y0 = (bbox_y_q8 >> 8).max(0) as usize;
    let x1 = ((bbox_x_q8 + bbox_w_q8) >> 8).min(w as i32).max(0) as usize;
    let y1 = ((bbox_y_q8 + bbox_h_q8) >> 8).min(h as i32).max(0) as usize;
    if x0 >= x1 || y0 >= y1 {
        return;
    }

    let (gw, gh) = (g.w as i32, g.h as i32);
    let data_base = g.offset as usize;

    for sy in y0..y1 {
        for sx in x0..x1 {
            let src_x0 = (sx as i32 * 256 - bbox_x_q8).max(0);
            let src_y0 = (sy as i32 * 256 - bbox_y_q8).max(0);
            let src_x1 = ((sx as i32 + 1) * 256 - bbox_x_q8).min(bbox_w_q8);
            let src_y1 = ((sy as i32 + 1) * 256 - bbox_y_q8).min(bbox_h_q8);
            if src_x0 >= src_x1 || src_y0 >= src_y1 {
                continue;
            }

            let mut cov_sum: i64 = 0;
            let mut area: i64 = 0;
            let ix0 = src_x0 / 256;
            let ix1 = ((src_x1 + 255) / 256).min(gw);
            let iy0 = src_y0 / 256;
            let iy1 = ((src_y1 + 255) / 256).min(gh);
            for iy in iy0..iy1 {
                let cell_y0 = iy * 256;
                let y_lo = src_y0.max(cell_y0);
                let y_hi = src_y1.min((iy + 1) * 256);
                if y_lo >= y_hi {
                    continue;
                }
                let ry = (y_hi - y_lo) as i64;
                for ix in ix0..ix1 {
                    let x_lo = src_x0.max(ix * 256);
                    let x_hi = src_x1.min((ix + 1) * 256);
                    if x_lo >= x_hi {
                        continue;
                    }
                    let rx = (x_hi - x_lo) as i64;
                    let cov = data[data_base + iy as usize * gw as usize + ix as usize];
                    cov_sum += cov as i64 * rx * ry;
                    area += rx * ry;
                }
            }

            if area > 0 && cov_sum > 0 {
                let cov_f = cov_sum as f32 / (area as f32 * 255.0);
                if cov_f > 0.005 {
                    let px = &mut fb[sy * w + sx];
                    *px = color::blend_over_lin(*px, color, alpha * cov_f);
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn index_for_finds_sample_glyphs() {
        assert_ne!(index_for('山' as u32), 0);
        assert_ne!(index_for('月' as u32), 0);
    }

    #[test]
    fn unknown_cp_returns_zero() {
        assert_eq!(index_for(0x9999_9999), 0);
    }

    #[test]
    fn glyph_table_size_matches() {
        assert!(GLYPH_COUNT >= FONT_INDEX.len());
    }
}
