//! Embedded grayscale-coverage glyph renderer for inkflow.
//!
//! The pre-rendered glyph atlas lives in `glyph_table` (auto-generated by
//! `scripts/build_font.py` from `Noto Sans CJK JP`).  Two pre-rendered
//! buckets are stored: a "hero" bucket at 128 px em (the native size for
//! headline phrases), and a "body" bucket at 72 px em (used for smaller
//! text or downsamples).  Each glyph carries real per-pixel coverage
//! (8-bit alpha) so `draw_glyph` composites with smooth, font-quality
//! edges — no upscaling of a tiny 1-bit mask.
//!
//! All glyph data is `pub const`, so the renderer makes no allocations
//! and ships with zero runtime dependencies.

use crate::color;

/// Re-export the pre-rendered glyph descriptor.
pub use crate::glyph_table::Glyph;

/// Native em size of the hero bucket (used for default scale math).
pub const HERO_EM_PX: u16 = crate::glyph_table::HERO_EM_PX;
/// Native em size of the body bucket.
pub const BODY_EM_PX: u16 = crate::glyph_table::BODY_EM_PX;

/// Re-export the tables for callers that need to read metrics directly.
pub use crate::glyph_table::{
    BODY_DATA, BODY_NOTDEF, BODY_TABLE, FONT_INDEX, GLYPH_COUNT, HERO_DATA, HERO_NOTDEF, HERO_TABLE,
};

// ============================================================
// Bucket selection
// ============================================================

/// Q8 fixed-point scale at which the body bucket is the native rendering size.
/// With hero=128 and body=72, body native = 256 * 72 / 128 = 144.
/// We default to using the hero bucket for everything — its 128 px native
/// glyphs downsample cleanly to supporting sizes, while body bucket glyphs
/// show positioning artifacts at small scale_q8 values.
const BODY_BUCKET_THRESHOLD_Q8: u32 = 60;

/// Pre-rendered bucket the caller wants to draw from.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Bucket {
    /// 128 px em — native for headline phrases.
    Hero,
    /// 72 px em — smaller body text.
    Body,
}

impl Bucket {
    /// Native em size of the bucket in source pixels.
    #[inline]
    pub const fn em_px(self) -> u16 {
        match self {
            Bucket::Hero => HERO_EM_PX,
            Bucket::Body => BODY_EM_PX,
        }
    }

    /// Pick the bucket that minimises resampling for `scale_q8` (Q8 fixed-
    /// point scale relative to the hero bucket's native em: 256 = hero em).
    #[inline]
    pub const fn pick_for_scale(scale_q8: u32) -> Bucket {
        if scale_q8 < BODY_BUCKET_THRESHOLD_Q8 {
            Bucket::Body
        } else {
            Bucket::Hero
        }
    }
}

/// 2-D point in pixel coordinates (top-left origin, integer pixels).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Point {
    pub x: i32,
    pub y: i32,
}

impl Point {
    #[inline]
    pub const fn new(x: i32, y: i32) -> Self {
        Self { x, y }
    }
}

/// Binary-search codepoint → glyph slot.  Returns 0 (notdef) for unmapped.
pub fn index_for(cp: u32) -> u8 {
    let mut lo = 0usize;
    let mut hi = FONT_INDEX.len();
    while lo < hi {
        let mid = (lo + hi) >> 1;
        let e = &FONT_INDEX[mid];
        if e.cp < cp {
            lo = mid + 1;
        } else if e.cp > cp {
            hi = mid;
        } else {
            return e.slot as u8;
        }
    }
    0
}

/// Backward-compatibility shim: the legacy 1-bit API exposed
/// `bitmap_width()` (24).  We now return the hero bucket's em size so
/// legacy callers still get a sensible number.
#[inline]
pub const fn bitmap_width() -> usize {
    HERO_EM_PX as usize
}
#[inline]
pub const fn bitmap_height() -> usize {
    HERO_EM_PX as usize
}

// ============================================================
// Composite — single glyph (uses nearest bucket, area sampling)
// ============================================================

/// Look up the pre-resolved glyph descriptor + atlas data for `glyph_idx` at
/// `bucket`.  Returns the notdef when the slot is 0.
#[inline]
fn lookup(bucket: Bucket, slot: usize) -> (&'static Glyph, &'static [u8]) {
    match bucket {
        Bucket::Hero => {
            if slot == 0 {
                (&HERO_NOTDEF, &HERO_DATA[..])
            } else {
                (&HERO_TABLE[slot], &HERO_DATA[..])
            }
        }
        Bucket::Body => {
            if slot == 0 {
                (&BODY_NOTDEF, &BODY_DATA[..])
            } else {
                (&BODY_TABLE[slot], &BODY_DATA[..])
            }
        }
    }
}

/// Render a glyph into the framebuffer.
///
/// `fx`/`fy` are Q8 fixed-point pixel coordinates of the **pen position** and
/// **baseline** respectively.  `scale_q8` is Q8 fixed-point scale relative to
/// the **hero bucket's native em**: `256` = target equals hero em (no scaling).
/// The nearest pre-rendered bucket is chosen automatically; the renderer
/// area-samples when the target is smaller than the bucket and clips (via
/// nearest-neighbor-flavoured area) when it's larger.
#[allow(clippy::too_many_arguments)]
pub fn draw_glyph(
    fb: &mut [u32],
    w: usize,
    h: usize,
    glyph_idx: u8,
    color: u32,
    _glow: u32,
    fx: i32,
    fy: i32,
    scale_q8: u32,
    alpha: f32,
) {
    if alpha <= 0.0 {
        return;
    }
    let bucket = Bucket::pick_for_scale(scale_q8);
    let (g, data) = lookup(bucket, glyph_idx as usize);
    composite_glyph(fb, w, h, g, data, bucket, color, fx, fy, scale_q8, alpha);
}

// ============================================================
// Composite — high-level phrase entry
// ============================================================

/// Render a UTF-8 phrase in a single horizontal line, drawing each glyph
/// from `bucket` at its native em size (no resampling).  `position` is the
/// pixel coordinate of the first character's pen (top-left origin); the
/// baseline sits at `position.y`.  Advances use the glyph's own advance
/// metric, scaled to the bucket's native em.
///
/// `alpha` modulates per-pixel ink coverage (already-AAd ink is scaled).
/// `color` is the ink colour.
#[allow(clippy::too_many_arguments)]
pub fn draw_phrase(
    fb: &mut [u32],
    w: usize,
    h: usize,
    phrase: &str,
    position: Point,
    bucket: Bucket,
    color: u32,
    alpha: f32,
) {
    if alpha <= 0.0 {
        return;
    }
    // Render at the bucket's native em — scale_q8 = "relative to hero em" so
    // we need to scale up for the smaller body bucket.
    let scale_q8 = (bucket.em_px() as u32) * 256u32 / (HERO_EM_PX as u32);
    // One source pixel in screen Q8 — same factor composite_glyph uses. At a
    // bucket's native em this is 256 (1:1). Advance is stored in the bucket's
    // source pixels, so it must be converted with this step, not scale_q8
    // alone (which for Body shrank a 72 px advance to ~40 px and piled the
    // characters on top of each other).
    let src_step_q8 = (scale_q8 as i32) * (HERO_EM_PX as i32) / (bucket.em_px() as i32);
    let mut pen_x_q8 = position.x * 256;
    let fy = position.y * 256;
    let data: &'static [u8] = match bucket {
        Bucket::Hero => &HERO_DATA,
        Bucket::Body => &BODY_DATA,
    };
    for ch in phrase.chars() {
        let slot = index_for(ch as u32) as usize;
        let (g, _) = lookup(bucket, slot);
        composite_glyph(
            fb, w, h, g, data, bucket, color, pen_x_q8, fy, scale_q8, alpha,
        );
        // Advance pen by glyph.advance in the bucket's source pixels,
        // converted to screen Q8.
        pen_x_q8 += (g.advance as i32) * src_step_q8;
    }
}

// ============================================================
// Composite — inner helper
// ============================================================

/// Inner composite routine.  Caller has already chosen bucket + looked up the
/// glyph descriptor and atlas data slice.
///
/// `fx` is the pen position in Q8 fixed-point pixels.  `fy` is the baseline
/// in Q8 fixed-point pixels.  `scale_q8` is the target scale in Q8, relative
/// to the hero bucket's native em (256 = 128 px on screen).  The renderer
/// area-samples when the target is smaller than the bucket's native em; when
/// it is larger, the area sampler naturally upscales with smooth coverage.
#[allow(clippy::too_many_arguments)]
fn composite_glyph(
    fb: &mut [u32],
    w: usize,
    h: usize,
    g: &Glyph,
    data: &[u8],
    bucket: Bucket,
    color: u32,
    fx: i32,
    fy: i32,
    scale_q8: u32,
    alpha: f32,
) {
    // The bucket's source pixels are in bucket.em_px() units (128 for Hero,
    // 72 for Body).  scale_q8 is relative to hero em (256 = 128 px).
    // Conversion: target_px = source_px * scale_q8 * hero_em / (256 * bucket_em).
    // In Q8 units (target_px * 256):
    //   target_q8 = source_px * scale_q8 * hero_em / bucket_em
    let bucket_em = bucket.em_px() as i32;
    let hero_em = HERO_EM_PX as i32;
    let mul = scale_q8 as i32; // * hero_em / bucket_em folded into w_q8 below.

    // Position: pen at (fx>>8, fy>>8); baseline at (pen.x, fy>>8).
    // Top-left of bbox in screen-space, in Q8 units:
    //   bbox_top_left_x = fx + bearing_x * scale_q8
    //   bbox_top_left_y = fy - bearing_y * scale_q8
    let bbox_x_q8 = fx + (g.bearing_x as i32) * mul * hero_em / bucket_em;
    let bbox_y_q8 = fy - (g.bearing_y as i32) * mul * hero_em / bucket_em;
    let bbox_w_q8 = (g.w as i32) * mul * hero_em / bucket_em;
    let bbox_h_q8 = (g.h as i32) * mul * hero_em / bucket_em;

    if bbox_w_q8 <= 0 || bbox_h_q8 <= 0 {
        return;
    }

    let x0 = (bbox_x_q8 >> 8).max(0) as usize;
    let y0 = (bbox_y_q8 >> 8).max(0) as usize;
    let x1 = ((bbox_x_q8 + bbox_w_q8) >> 8).min(w as i32).max(0) as usize;
    let y1 = ((bbox_y_q8 + bbox_h_q8) >> 8).min(h as i32).max(0) as usize;
    if x0 >= x1 || y0 >= y1 {
        return;
    }

    // The source-space step between adjacent source pixels in Q8 units.
    // Each source pixel occupies `scale_q8 / (hero_em / bucket_em)` Q8 in
    // screen space — at scale_q8=256 (full hero em), one source pixel equals
    // one output pixel (256 Q8). At scale_q8=77 (0.30 em) each source pixel
    // equals 0.30 output pixels (77 Q8) so area sampling can average ~3.3
    // source pixels per output pixel. Earlier versions used a fixed
    // 256*hero_em/bucket_em which forced 1:1 sampling at every scale and
    // truncated the bottom of every downscaled glyph to the top rows of the
    // atlas — explaining the "fragment only at the top" look.
    let src_step_q8 = (scale_q8 as i32) * hero_em / bucket_em;

    let gw = g.w as i32;
    let gh = g.h as i32;
    let data_base = g.offset as usize;

    for sy in y0..y1 {
        for sx in x0..x1 {
            // Source-space rect (Q8 units, integer) for this output pixel.
            let sxa = sx as i32 * 256 - bbox_x_q8;
            let sya = sy as i32 * 256 - bbox_y_q8;
            let sxb = (sx as i32 + 1) * 256 - bbox_x_q8;
            let syb = (sy as i32 + 1) * 256 - bbox_y_q8;
            if sxa >= bbox_w_q8 || sya >= bbox_h_q8 {
                continue;
            }
            let src_x0 = sxa.max(0);
            let src_y0 = sya.max(0);
            let src_x1 = sxb.min(bbox_w_q8);
            let src_y1 = syb.min(bbox_h_q8);
            if src_x0 >= src_x1 || src_y0 >= src_y1 {
                continue;
            }

            // Walk the source pixels overlapped by this output pixel and
            // sum coverage weighted by overlap area (rx*ry).
            let mut cov_sum: i64 = 0;
            let mut area: i64 = 0;
            let ix0 = src_x0 / src_step_q8;
            let ix1 = (src_x1 + src_step_q8 - 1) / src_step_q8;
            let iy0 = src_y0 / src_step_q8;
            let iy1 = (src_y1 + src_step_q8 - 1) / src_step_q8;
            let mut iy = iy0;
            while iy < iy1 && iy < gh {
                let cell_y0 = iy * src_step_q8;
                let cell_y1 = ((iy + 1) * src_step_q8).min(gh * src_step_q8);
                let y_lo = src_y0.max(cell_y0);
                let y_hi = src_y1.min(cell_y1);
                if y_lo < y_hi {
                    let ry = (y_hi - y_lo) as i64;
                    let mut ix = ix0;
                    while ix < ix1 && ix < gw {
                        let cell_x0 = ix * src_step_q8;
                        let cell_x1 = ((ix + 1) * src_step_q8).min(gw * src_step_q8);
                        let x_lo = src_x0.max(cell_x0);
                        let x_hi = src_x1.min(cell_x1);
                        if x_lo < x_hi {
                            let rx = (x_hi - x_lo) as i64;
                            // 8-bit coverage — no unpacking needed.
                            let cov =
                                data[data_base + (iy as usize) * (gw as usize) + (ix as usize)];
                            cov_sum += cov as i64 * rx * ry;
                            area += rx * ry;
                        }
                        ix += 1;
                    }
                }
                iy += 1;
            }

            if area > 0 && cov_sum > 0 {
                // cov_sum / area is in 0..255 units.  Normalise to 0..1.
                let cov_f = (cov_sum as f32) / ((area as f32) * 255.0);
                if cov_f > 0.005 {
                    let a = alpha * cov_f;
                    let px = &mut fb[sy * w + sx];
                    *px = color::blend_over_lin(*px, color, a);
                }
            }
        }
    }
}

// ============================================================
// Tests
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn index_for_finds_sample_glyphs() {
        let sample = [
            0x6708u32, 0x591C, 0x5BD2, 0x5C71, 0x4E91, 0x6C34, 0x5149, 0x68A6,
        ];
        for cp in sample {
            assert!(index_for(cp) > 0, "missing glyph for U+{cp:04X}");
        }
    }

    #[test]
    fn unknown_cp_returns_zero() {
        // Private-use area shouldn't be in our table.
        assert_eq!(index_for(0xE000), 0);
    }

    #[test]
    fn glyph_table_size_matches() {
        assert!(GLYPH_COUNT > 100, "expected >100 glyphs, got {GLYPH_COUNT}");
    }

    #[test]
    fn bucket_threshold_sensible() {
        // The threshold (60) is set so we always use the Hero bucket — its
        // 128 px native glyphs area-sample down to small scales cleanly. Body
        // bucket glyphs (72 px native) are kept in the atlas for future use
        // but the auto-picker should never choose them at the scales we use
        // today. Verify a few representative scales.
        assert_eq!(Bucket::pick_for_scale(256), Bucket::Hero);
        assert_eq!(Bucket::pick_for_scale(200), Bucket::Hero);
        assert_eq!(Bucket::pick_for_scale(144), Bucket::Hero);
        // The threshold picks Body only for very small scales (below 60),
        // which we don't currently use. Sanity check the picker is monotone.
        for s in [70u32, 80, 100, 144, 200, 256] {
            assert_eq!(Bucket::pick_for_scale(s), Bucket::Hero);
        }
    }
}
